// Порівняйте два фрагменти коду.

// В першому використовується finally для виконання коду після try...catch:

// try {
//   виконання коду
// } catch (err) {
//   обробка помилок
// } finally {
//   очищення ресурсів
// }
// В другому коді очищення відбувається одразу після try...catch:

// try {
//   виконання коду
// } catch (err) {
//   обробка помилок
// }

// очищення ресурсів
// Очищення ресурсів потрібно виконати після роботи не залежно від наявності помилки.

// Чи є якійсь переваги використання finally, чи обидва фрагменти коду однакові? Якщо є різниця – наведіть приклади використання.

// finaly завжди гарантує виконання коду
